# Generated by Django 5.0.4 on 2024-04-20 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disponible', models.BooleanField(default=True)),
                ('perdu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auteur', models.CharField(max_length=128)),
                ('titre', models.CharField(max_length=128)),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exemplaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appBibliotheque.exemplaire')),
            ],
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires_livre', to='appBibliotheque.livre'),
        ),
    ]
