# Generated by Django 5.0.4 on 2024-04-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='categories',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
