# Generated by Django 5.0.3 on 2024-04-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBibliotheque', '0002_livre_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunter',
            name='accepter',
            field=models.BooleanField(default=False),
        ),
    ]
