# Generated by Django 5.0.3 on 2024-05-08 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBibliotheque', '0003_emprunter_accepter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeEmprunt',
            fields=[
                ('id_demande', models.AutoField(primary_key=True, serialize=False)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('acceptee', models.BooleanField(default=False)),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appBibliotheque.exemplaire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
